---
baseurl: "/"
theme: "stage"
metaDataFormat: "yaml"
params:

  lang: en-US
  copyright: Made with <i class="fa fa-heart-o"></i> by <a href="http://noahlange.com">Noah Lange</a>. Powered by <a href="http://hugo.spf13.com">Hugo</a>.

  # Website information
  title: "Stage"
  subtitle: "A Hugo theme for musicians and creative types."
  coverimage: "/images/stage.jpg"

  # Social information
  social:
    facebook: "http://facebook.com/"
    soundcloud: "http://soundcloud.com/"
    reverbnation: "http://reverbnation.com/"
    contact: "/"

  # Artist information
  authors:
    stage:
      name: "Stage"
      description: "Enter an artist description here."
      image: "/images/avatar.png"
      link: "/"

  # Navbar links
  navbar:
    blog: "/post/"
    bio: "/"
    music: "/album/"
    events: "/event/"
    media: "/media/"

  fonts: "Lato:300,500,700"
  maps: "true"
---
